#ifndef __LOCKBOX_CONTROLLER_RQ_VALID_PROTOCOL_VALUES_H__
#define __LOCKBOX_CONTROLLER_RQ_VALID_PROTOCOL_VALUES_H__

static const char PROTOVER_ATTR_VALUE[] = "1.1";

static const char SERIAL_ATTR_VALUE[] = "UDH-TX144";

#endif //__LOCKBOX_CONTROLLER_RQ_VALID_PROTOCOL_VALUES_H__
